
// This file has been generated by genreflex with the --capabilities option
static  const char* clnames[] = {
//--Begin tmp/slc6_amd64_gcc530/src/MEMDataFormats/MEMDataFormats/src/MEMDataFormatsMEMDataFormats/a/MEMDataFormatsMEMDataFormats_xr.cc_tmp
 "LCGReflex/reco::MEMResult",
 "LCGReflex/std::vector<reco::MEMResult>",
 "LCGReflex/vector<reco::MEMResult>",
 "LCGReflex/edm::Wrapper<std::vector<reco::MEMResult> >",
 "LCGReflex/edm::Wrapper<vector<reco::MEMResult> >",
 "LCGReflex/edm::Ref<std::vector<reco::MEMResult>,reco::MEMResult,edm::refhelper::FindUsingAdvance<std::vector<reco::MEMResult>,reco::MEMResult> >",
 "LCGReflex/edm::Ref<vector<reco::MEMResult>,reco::MEMResult,edm::refhelper::FindUsingAdvance<vector<reco::MEMResult>,reco::MEMResult> >",
 "LCGReflex/edm::RefProd<std::vector<reco::MEMResult> >",
 "LCGReflex/edm::RefProd<vector<reco::MEMResult> >",
 "LCGReflex/edm::RefVector<std::vector<reco::MEMResult>,reco::MEMResult,edm::refhelper::FindUsingAdvance<std::vector<reco::MEMResult>,reco::MEMResult> >",
 "LCGReflex/edm::RefVector<vector<reco::MEMResult>,reco::MEMResult,edm::refhelper::FindUsingAdvance<vector<reco::MEMResult>,reco::MEMResult> >",
 "LCGReflex/reco::IntegralResult",
 "LCGReflex/RunConfig",
//--End   tmp/slc6_amd64_gcc530/src/MEMDataFormats/MEMDataFormats/src/MEMDataFormatsMEMDataFormats/a/MEMDataFormatsMEMDataFormats_xr.cc_tmp
//--Final End
};

extern "C" void SEAL_CAPABILITIES (const char**& names, int& n )
{
names = clnames;
n = sizeof(clnames)/sizeof(char*);
}
